### ISSUE TITLE
f12查看/api/server接口返回结果为空

### ISSUE THREAD

**Issue by lcyan** [hamster1963/nezha-dash#90]
nezha和nezha-dash都是用docker部署
![image](https://github.com/user-attachments/assets/bcecf429-2c11-4cbf-b6a8-eee27e9c40d1)

我自己调接口可以返回数据:

```bash
curl --location --request GET 'http://172.19.0.2:80/api/v1/server/list' \
--header 'Authorization: xxxxxxxxxxxxxxx' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: 172.19.0.2:80' \
--header 'Connection: keep-alive'
```

```json
{
    "code": 0,
    "message": "success",
    "result": [
        {
            "id": 4,
            "name": "腾讯云",
            "tag": "腾讯云",
            "last_active": 1729736690,
            "ipv4": "xxxx",
            "ipv6": "",
            "valid_ip": "xxxxx",
            "display_index": 0,
            "hide_for_guest": false
        }
    ]
}
```

.env配置文件
![image](https://github.com/user-attachments/assets/e64da9f1-1291-4666-b58a-229ed8dafa28)

**Comment by hamster1963** [comment]
请检查容器内是否可以调通这个IP，可能是容器网段不一致。

**Comment by hamster1963** [comment]
或者尝试在docker-compose.yml中添加network_mode: "host"
```
version: "3"
services:
  nezha-dash:
    container_name: nezha-dash
    image: hamster1963/nezha-dash:latest
    volumes:
      - ./.env:/app/.env
    restart: always
    network_mode: "host"
    ports:
      - "4123:3000"
```
